src/Entity/Donation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\Base\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DonationRepository")
 * @ORM\Table(name="donations")
 */
class Donation
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $amount;

    /**
     * @ORM\Column(type="text")
     */
    private $FirstName;

    /**
     * @ORM\Column(type="text")
     */
    private $LastName;

    /**
     * @ORM\Column(type="text")
     */
    private $Country;

    /**
     * @ORM\Column(type="text")
     */
    private $City;

    /**
     * @ORM\Column(type="text")
     */
    private $State;

    /**
     * @ORM\Column(type="text")
     */
    private $Code;

    /**
     * @ORM\Column(type="text")
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="text")
     */
    private $phone;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $employer;

    /**
     * @ORM\Column(type="text")
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $certificate;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountType;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountNumber;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountHolder;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $expiryMonth;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $expiryYear;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $cvv;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $transactionId;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $transactionCode;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $transactionStatus;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $period;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $term;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $startMonth;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $startYear;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $mailSent;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->State;
    }

    public function setState(string $State): self
    {
        $this->State = $State;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmployer(): ?string
    {
        return $this->employer;
    }

    public function setEmployer(?string $employer): self
    {
        $this->employer = $employer;

        return $this;
    }

    public function getCertificate(): ?string
    {
        return $this->certificate;
    }

    public function setCertificate(string $certificate): self
    {
        $this->certificate = $certificate;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    public function getAccountType()
    {
        return $this->accountType;
    }

    public function setAccountType($accountType)
    {
        $this->accountType = $accountType;

        return $this;
    }

    public function getAccountNumber()
    {
        return $this->accountNumber;
    }

    public function setAccountNumber($accountNumber)
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    public function getAccountHolder()
    {
        return $this->accountHolder;
    }

    public function setAccountHolder($accountHolder)
    {
        $this->accountHolder = $accountHolder;

        return $this;
    }

    public function getExpiryMonth()
    {
        return $this->expiryMonth;
    }

    public function setExpiryMonth($expiryMonth)
    {
        $this->expiryMonth = $expiryMonth;

        return $this;
    }

    public function getExpiryYear()
    {
        return $this->expiryYear;
    }

    public function setExpiryYear($expiryYear)
    {
        $this->expiryYear = $expiryYear;

        return $this;
    }

    public function getCvv()
    {
        return $this->cvv;
    }

    public function setCvv($cvv)
    {
        $this->cvv = $cvv;

        return $this;
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function setComments($comments)
    {
        $this->comments = $comments;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    /**
     * @param mixed $transactionId
     */
    public function setTransactionId($transactionId)
    {
        $this->transactionId = $transactionId;
    }

    /**
     * @return mixed
     */
    public function getTransactionStatus()
    {
        return $this->transactionStatus;
    }

    /**
     * @param mixed $transactionStatus
     */
    public function setTransactionStatus($transactionStatus): void
    {
        $this->transactionStatus = $transactionStatus;
    }

    /**
     * @return mixed
     */
    public function getTransactionCode()
    {
        return $this->transactionCode;
    }

    /**
     * @param mixed $transactionCode
     */
    public function setTransactionCode($transactionCode)
    {
        $this->transactionCode = $transactionCode;
    }

    /**
     * @return mixed
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * @param mixed $period
     */
    public function setPeriod($period)
    {
        $this->period = $period;
    }

    /**
     * @return mixed
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * @param mixed $term
     */
    public function setTerm($term)
    {
        $this->term = $term;
    }

    /**
     * @return mixed
     */
    public function getStartMonth()
    {
        return $this->startMonth;
    }

    /**
     * @param mixed $startMonth
     */
    public function setStartMonth($startMonth)
    {
        $this->startMonth = $startMonth;
    }

    /**
     * @return mixed
     */
    public function getStartYear()
    {
        return $this->startYear;
    }

    /**
     * @param mixed $startYear
     */
    public function setStartYear($startYear)
    {
        $this->startYear = $startYear;
    }

    /**
     * @return mixed
     */
    public function getMailSent()
    {
        return $this->mailSent;
    }

    /**
     * @param mixed $mailSent
     */
    public function setMailSent($mailSent)
    {
        $this->mailSent = $mailSent;
    }
}

src/Controller/PaypalPayFlowController.php
<?php

namespace App\Controller;

use App\Entity\Donation;
use App\Entity\Certificate;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\PaypalPayFlow;
use App\Service\MailService;
use Symfony\Component\HttpFoundation\Request;

class PaypalPayFlowController extends AbstractController
{
    private $mailer;

    /**
     * PaypalPayFlowController constructor.
     * @param MailService $mailer
     */
    public function __construct(MailService $mailer)
    {
        $this->mailer = $mailer;
    }

    /**
     * @Route("/singlepayflow/{id}", name="singlepayflow")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function onetime(Request $request)
    {
        $id = $request->attributes->get('id');

        $donation = $this->getDoctrine()
            ->getRepository(Donation::class)
            ->find($id);

        $paypal = new PaypalPayFlow();
        $result = $paypal->runSingle($donation);

        $entityManager = $this->getDoctrine()->getManager();

        $number = substr($donation->getAccountNumber(), 12);
        $donation->setAccountNumber('************'.$number);
        $donation->setTransactionId($result[2]);
        $donation->setAccountType(null);
        $donation->setExpiryMonth(null);
        $donation->setExpiryYear(null);
        $donation->setCvv(null);
        $donation->setUpdatedAt(new \DateTime('now'));
        $donation->setTransactionCode($result[0]);
        $donation->setTransactionStatus($result[1]);

        $entityManager->persist($donation);

        $entityManager->flush();

        if($result[0] == 0){
            return $this->redirectToRoute('donepayflow', array('id' => $id ));
        }else{
            return $this->redirectToRoute('payment', array('id' => $id ));
        }
    }

    /**
     * @Route("/donepayflow", name="donepayflow")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function done(Request $request)
    {
        $id = $request->attributes->get('id');

        $donation = $this->getDoctrine()
            ->getRepository(Donation::class)
            ->find($id);

        if($donation->getMailSent() != 'sent'){
            if($donation->getCertificate() == 'Yes'){
                $certificate = $this->getDoctrine()
                    ->getRepository(Certificate::class)
                    ->findOneBy(['donationId'=>$id]);

                /** @var  $template */
                $template = $this->render("email/donation.html.twig", [
                    "donation" => $donation,
                    'certificate' => $certificate
                ]);
            }else{
                /** @var  $template */
                $template = $this->render("email/donation.html.twig", [
                    "donation" => $donation
                ]);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $donation->setMailSent('sent');

            $entityManager->persist($donation);

            $entityManager->flush();

            $this->mailer->sendDonationEmail($template, $donation->getEmail());
        }

        return $this->render('paypal-pay-flow/thanks.html.twig', [
            'donation' => $donation,
        ]);
    }

    /**
     * @Route("/monthlypayflow/{id}", name="monthlypayflow")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function monthly(Request $request)
    {
        $id = $request->attributes->get('id');

        $donation = $this->getDoctrine()
            ->getRepository(Donation::class)
            ->find($id);

        $paypal = new PaypalPayFlow();
        $result = $paypal->runMonthly($donation);

        $entityManager = $this->getDoctrine()->getManager();

        $number = substr($donation->getAccountNumber(), 12);
        $donation->setAccountNumber('************'.$number);
        $donation->setTransactionId($result[2]);
        $donation->setAccountType(null);
        $donation->setExpiryMonth(null);
        $donation->setExpiryYear(null);
        $donation->setCvv(null);
        $donation->setUpdatedAt(new \DateTime('now'));
        $donation->setTransactionCode($result[0]);
        $donation->setTransactionStatus($result[1]);

        $entityManager->persist($donation);

        $entityManager->flush();

        if($result[0] == 0){
            return $this->redirectToRoute('donepayflow', array('id' => $id ));
        }else{
            return $this->redirectToRoute('payment', array('id' => $id ));
        }
    }
}

templates/paypal-pay-flow/donation-review-certificate.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>Armenia Tree Project - Donation Review</title>{% endblock %}

{% block body %}
    <!--Single News-->

    <section class="donation-review-page">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Transaction completed successfully</h1>
                    <p>Thank you for you donation</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="donation-details">
                        <div>
                            <p>Donation</p>
                            <p>Designation</p>
                            <p>Number of Payments</p>
                            <p>Certificate</p>
                            <p>Donor Name</p>
                            <p>Donor E-mail</p>
                            <p>Comments</p>
                            <p>Billing Name</p>
                            <p>Address</p>
                        </div>
                        <div class="donated-user-details">
                            <p>$ {{ donation.amount }}</p>
                            <p>Backyard Nurseries</p>
                            <p>{{ donation.type }}</p>
                            <p>{{ donation.certificate }}</p>
                            <p>{{ donation.firstName }} {{ donation.lastName }}</p>
                            <p>{{ donation.email }}</p>
                            <p>{{ donation.comments }}</p>
                            <p>{{ donation.firstName }} {{ donation.lastName }}</p>
                            <p>{{ donation.address }}, {{ donation.city }}, {{ donation.state }}, {{ donation.code }}, {{ donation.country }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--Footer Section-->

    <section class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">Glossary</a>
                        </li>

                        <li>
                            <a href="{{ path('contact') }}">Contact Us</a>
                        </li><li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">FAQ</a>
                        </li>
                        <li class="hidden">
                            <a href="#">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <p><span> Armenia Tree Project </span> <br> 400 West Cummings Park <br> Suite 3900, Woburn, MA 01801 USA
                        <br> 617-926-TREE (8733)</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <p class="copyright-text">&copy; Copyright 1994-2019 Armenia Tree Project, a project of Armenian
                        Assembly of America. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right  social">
                    <p class="hashtag">#GetRooted</p>
                    <a href="#">
                        <img src="./img/facebook-logo.svg" alt="linkedin">
                    </a>
                    <a href="#">
                        <img src="./img/twitter-logo.svg" alt="facebook">
                    </a>
                    <a href="#">
                        <img src="./img/instagram-logo.svg" alt="twitter">
                    </a>
                    <a href="#">
                        <img src="./img/youtube.svg" alt="twitter">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>

    <!-- Custom Js Files-->
    <script src="{{ asset('js/main.js') }}"></script>

{% endblock %}

templates/paypal-pay-flow/thanks.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>Armenia Tree Project - Donation Review</title>{% endblock %}

{% block body %}
    <!--Single News-->

    <section class="donation-review-page">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Thanks for your Donation!</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="donation-details">
                        <div>
                            <div>
                                <p>Donation</p>
                                <p class="donated-user-details">$ {{ donation.amount }}</p>
                            </div>
                            <div>
                                <p>Designation</p>
                                <p class="donated-user-details">Backyard Nurseries</p>
                            </div>
                            <div>
                                <p>Number of Payments</p>
                                <p class="donated-user-details">{{ donation.type }}</p>
                            </div>
                            <div>
                                <p>Certificate</p>
                                <p class="donated-user-details">{{ donation.certificate }}</p>
                            </div>
                            <div>
                                <p>Donor Name</p>
                                <p class="donated-user-details">{{ donation.firstName }} {{ donation.lastName }}</p>
                            </div>
                            <div>
                                <p>Donor E-mail</p>
                                <p class="donated-user-details">{{ donation.email }}</p>
                            </div>
                            <div>
                                <p>Comments</p>
                                <p class="donated-user-details">{{ donation.comments }}</p>
                            </div>
                            <div>
                                <p>Billing Name</p>
                                <p class="donated-user-details">{{ donation.firstName }} {{ donation.lastName }}</p>
                            </div>
                            <div>
                                <p>Billing Address</p>
                                <p class="donated-user-details">{{ donation.address }}, {{ donation.city }}, {{ donation.state }}, {{ donation.code }}, {{ donation.country }}</p>
                            </div>
                            <div>
                                <p>Special Instruction</p>
                                {% if donation.comments is not null %}
                                    <p class="donated-user-details">{{ donation.comments }}</p>
                                {% else %}
                                    <p class="donated-user-details">N/A</p>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--Footer Section-->

    <section class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">Glossary</a>
                        </li>

                        <li>
                            <a href="{{ path('contact') }}">Contact Us</a>
                        </li><li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">FAQ</a>
                        </li>
                        <li class="hidden">
                            <a href="#">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <p><span> Armenia Tree Project </span> <br> 400 West Cummings Park <br> Suite 3900, Woburn, MA 01801 USA
                        <br> 617-926-TREE (8733)</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <p class="copyright-text">&copy; Copyright 1994-2019 Armenia Tree Project, a project of Armenian
                        Assembly of America. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right  social">
                    <p class="hashtag">#GetRooted</p>
                    <a href="#">
                        <img src="../img/facebook-logo.svg" alt="linkedin">
                    </a>
                    <a href="#">
                        <img src="../img/twitter-logo.svg" alt="facebook">
                    </a>
                    <a href="#">
                        <img src="../img/instagram-logo.svg" alt="twitter">
                    </a>
                    <a href="#">
                        <img src="../img/youtube.svg" alt="twitter">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>

    <!-- Custom Js Files-->
    <script src="{{ asset('js/main.js') }}"></script>

{% endblock %}